FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/mulandibarakaa/cherry-trees /root/mulandibarakaa/cherry-trees
WORKDIR /root/mulandibarakaa/cherry-trees/
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
 
